# Site settings
title: Ryan Newman
email: ranewman@uwaterloo.ca
description: > # this means to ignore newlines until "baseurl:"
  Hello I am Ryan Newman and this is my personal website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
github_username:  ryannewman2828

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown